# Generated by Django 5.2.6 on 2025-10-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='other_club_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
