# Generated by Django 5.2.6 on 2025-10-06 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_expensetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentout',
            name='expense_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.expensetype'),
        ),
        migrations.AddField(
            model_name='paymentout',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
