# Generated by Django 5.2.6 on 2025-10-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_paymentout_expense_type_paymentout_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
