# Generated by Django 5.2.6 on 2025-10-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_account_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentout',
            name='expense_type',
            field=models.CharField(default='Miscellaneous', max_length=255),
            preserve_default=False,
        ),
    ]
