# Generated by Django 5.2.6 on 2025-10-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_alter_paymentout_expense_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentin',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
